name: Order-Management-System CI/CD 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[frontend]')
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: cd orders-ui && npm install

      - name: Build React app
        run: cd orders-ui && npm run build
 
  build-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[backend]')
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: cd orders-service && npm install

      - name: Run backend build
        run: cd orders-service && npm run build
