name: Order-Management-System CI/CD 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[frontend]')
    defaults:
      run:
        working-directory: order-ui

      strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
 
  backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[backend]')
    defaults:
      run:
        working-directory: order-service
      strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]
 
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm

        - name: Install dependencies
          run: npm install

        - name: Build React app
          run: npm run build
 