name: CI/CD for OMS with ReactJs-frontend, Nodejs-backend and Appwrite-services for database, storage, and messaging.

on:
  push:
    branches: [ "master" ]
    paths:
      - 'order-ui/**'
      - 'order-service/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'order-ui/**'
      - 'order-service/**'

jobs:
  frontend:
    if: contains(github.event.head_commit.message, '[frontend]')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-ui

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build 
       
  backend:
    if: contains(github.event.head_commit.message, '[backend]')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build 
  
 
    
  